[WIP] Parameters support and general refactoring of main.cpp
schizofrenicy/taio pull request #10
Opened 2023-11-19 17:52 UTC by H3w9VH3F4L4Tq5MbsfRi

2023-11-19 21:28 UTC, Sosssen requested changes
JESZCZE BĘDZIE PRZEPIĘKNIE

2023-11-19 21:28 UTC, Sosssen commented on graph.hpp
> +  static int get_distance(Graph &g1, Graph &g2, bool exact);
no i czm tutaj bez wartości domyślnej?

2023-11-19 21:28 UTC, Sosssen commented on graph.hpp
> +                                                   bool exact);
nie no dobra, już widzę co zrobiłeś, ale nie wiem po co usuwałeś do tego parametr, ciągle mógł zostać domyślny

ALE wsm to niech ci będzie, approved

2023-11-19 21:28 UTC, Sosssen commented on main.cpp
> +  int toReturn;
nie lubię nazwy `toReturn`, wolę `result`, ale jak się uprzesz to chociaż zrób w konwencji cpp: `to_return`

2023-11-19 21:28 UTC, Sosssen commented on main.cpp
> +  } else if (strcmp(argv[1], "-m") == 0 || strcmp(argv[1], "--mcs") == 0) {
tutaj dodaj jeszcze --MCS

2023-11-19 21:28 UTC, Sosssen commented on main.cpp
> +    std::cerr << "When in doubt, use --help" << std::endl;
jakoś nie siedzi mi to "when in doubt" ale nie mogę wymyślić nic lepszego

2023-11-19 21:28 UTC, Sosssen commented on main.cpp
> +  calculate_size(graphs, indx);
dobra generalnie to ja bym zostawił logikę do `size` i `clique` taką, jaka była

eweentualnie index to optional parameter i jeżeli nie podasz go, to liczy wszystkie z pliku, a jak podasz to liczy ten jeden

2023-11-19 21:28 UTC, Sosssen commented on main.cpp
> +  }
może zostawić to dopuszczalne? no policzy i wyjdzie 0 i chuj

2023-11-19 21:28 UTC, Sosssen commented on main.cpp
> +  }
ponownie, zostawiłbym

2023-11-19 21:28 UTC, Sosssen commented on main.cpp
> +  }
ponownie, nie dawałbym indexu jako MUST HAVE, tylko optional (inaczej przelicza wszystkie z pliku)

2023-11-19 21:28 UTC, Sosssen commented on main.cpp
> +  if (indx1 == indx2) {
i tutaj to by się generalnie przydało zrobić żeby więcej tych indexów było (ile wlezie)
no bo może być MCS pomiędzy więcej niż dwoma - dopisz na TODO w kodzie i zrobimy to w innym PR, bo to większa maszynka

2023-11-19 21:28 UTC, Sosssen commented on main.cpp
> +  } else if (strcmp(argv[1], "-m") == 0 || strcmp(argv[1], "--mcs") == 0) {
dobra i generalnie to mi mocno nie siedzi

funkcje `parse_*` nie powinny w środku obliczać już tych rzeczy (w sensie wywoływać `calculate_size` itp)
powinny zwrócić (jako wartość wynikową) czy się udało, i to robią, a wszystko co sparsowały zwrócić w out parameters, i tutaj sprawdzasz czy się udało, jak tak to dopiero wtedy wywołujesz dokładny `calculate` - funkcja parse jest do parsowania

2023-11-19 21:51 UTC, H3w9VH3F4L4Tq5MbsfRi commented on graph.hpp
> +                                                   bool exact);
no właśnie specjalnie usunełem, że nie byla niezgodnie z przeznaczeniem uzywana funkcja
unchanged

2023-11-19 21:51 UTC, H3w9VH3F4L4Tq5MbsfRi commented on graph.hpp
> +  static int get_distance(Graph &g1, Graph &g2, bool exact);
\/

2023-11-19 21:52 UTC, H3w9VH3F4L4Tq5MbsfRi commented on main.cpp
> +  } else if (strcmp(argv[1], "-m") == 0 || strcmp(argv[1], "--mcs") == 0) {
done

2023-11-19 21:54 UTC, H3w9VH3F4L4Tq5MbsfRi commented on main.cpp
> +  int toReturn;
done

2023-11-19 21:55 UTC, H3w9VH3F4L4Tq5MbsfRi commented on main.cpp
> +    std::cerr << "When in doubt, use --help" << std::endl;
specjalnie tak napisałem, żeby brzmiało jak np. ten warning jak pierwszy raz używasz sudo
jak coś wymyślisz lepszego to zmienię
unchanged

2023-11-19 21:57 UTC, H3w9VH3F4L4Tq5MbsfRi commented on main.cpp
> +  calculate_size(graphs, indx);
ja bym jednak zostawił tak jak zrobiłem, żeby była stała konwencja
jak jest wybór, to wybierasz
ale jak chcesz to mogę cofnąć
unchanged

2023-11-19 22:02 UTC, H3w9VH3F4L4Tq5MbsfRi commented on main.cpp
> +  }
tested
done

2023-11-19 22:02 UTC, H3w9VH3F4L4Tq5MbsfRi commented on main.cpp
> +  }
tested
done

2023-11-19 22:02 UTC, H3w9VH3F4L4Tq5MbsfRi commented on main.cpp
> +  }
ponownie, jak wyżej
unchanged

2023-11-19 22:06 UTC, H3w9VH3F4L4Tq5MbsfRi commented on main.cpp
> +  if (indx1 == indx2) {
wpisałem TODO

jak myśle, to wykonanie przez nas MCS więcej niż dwóch, to bedzie kolejne wywołanie tego MCS na produktach
ale nie wiem czy takie podejście jest poprawne
do analizy

2023-11-19 22:07 UTC, H3w9VH3F4L4Tq5MbsfRi commented on main.cpp
> +  } else if (strcmp(argv[1], "-m") == 0 || strcmp(argv[1], "--mcs") == 0) {
hmmm, no to będzie trochę do zmiany

2023-11-20 00:00 UTC, Sosssen commented on main.cpp
> +  calculate_size(graphs, indx);
zajmę się tym, to be resolved

2023-11-20 00:01 UTC, Sosssen commented on main.cpp
> +  }
tbd - TO BE DONE

2023-11-20 00:02 UTC, Sosssen commented on main.cpp
> +  if (indx1 == indx2) {
TYM TEŻ SIĘ ZAJMĘ (CHYBA)

2023-11-20 00:02 UTC, Sosssen commented on main.cpp
> +  } else if (strcmp(argv[1], "-m") == 0 || strcmp(argv[1], "--mcs") == 0) {
TO DO ROBOTY (ja, ja to zrobię)

2023-11-20 00:23 UTC, Sosssen commented on main.cpp
> +  } else if (strcmp(argv[1], "-m") == 0 || strcmp(argv[1], "--mcs") == 0) {
don (ty resolvujesz jak approved)

2023-11-20 01:17 UTC, Sosssen commented on main.cpp
> +  calculate_size(graphs, indx);
ogarnij jak jest, ty resolvujesz

2023-11-20 01:18 UTC, Sosssen commented on main.cpp
> +  }
jak wyżej, ty resolvujesz

2023-11-20 01:18 UTC, Sosssen commented on main.cpp
> +  if (indx1 == indx2) {
tutaj grubszy temat, wszystko poza mcs zrobiłem, tutaj mnie na razie pokonało, to be not resolved ŁAAAAAAA

2023-11-20 01:20 UTC, Sosssen commented on main.cpp
> +  if (indx1 == indx2) {
i tak, po prostu trzeba wołać mcs pierwszego i drugiego, potem wynik (induced graph) z trzecim itd itd
ale pokonało mnie printowanie tego wszystkiego XD jebaaaać

2023-11-20 20:08 UTC, H3w9VH3F4L4Tq5MbsfRi reviewed
NIE MOGĘ DAĆ CZERWONE BO TO MÓJ PR
ALE CZERWONE TU JEST

2023-11-20 20:08 UTC, H3w9VH3F4L4Tq5MbsfRi commented on main.cpp
> +int parse_size(int argc, char** argv, std::vector<Graph>& graphs, int& idx) {
jak już dodałeś sobie funkcję `try_parse_index()`, to użyj jej tutaj też

2023-11-20 20:08 UTC, H3w9VH3F4L4Tq5MbsfRi commented on main.cpp
> +  return 0;
teoretycznie unreachable return, więc powinno być `return 1;` i odpowiedni komentarz na `cerr`

2023-11-20 20:08 UTC, H3w9VH3F4L4Tq5MbsfRi commented on main.cpp
> +  return 0;
teoretycznie unreachable return, więc powinno być `return 1;` i odpowiedni komentarz na `cerr`

2023-11-20 20:09 UTC, H3w9VH3F4L4Tq5MbsfRi commented on main.cpp
> +  } else if (strcmp(argv[1], "-m") == 0 || strcmp(argv[1], "--mcs") == 0) {
parse_mcs jeszcze do przerobienia

2023-11-20 20:19 UTC, Sosssen commented on main.cpp
> +              << std::endl;
po chuju, wytłumaczone IRL

2023-11-20 20:56 UTC, Sosssen requested changes

2023-11-20 20:56 UTC, Sosssen commented on main.cpp
> +int parse_size(int argc, char** argv, std::vector<Graph>& graphs, int& idx) {
DON

2023-11-20 20:56 UTC, Sosssen commented on main.cpp
> +  if (argc == 4) {
NIE ZGADZAM SIĘ, POzdrawiam

2023-11-20 20:56 UTC, Sosssen commented on main.cpp
> +      for (int j = i; j < graphs.size(); j++) {
DON

2023-11-20 20:56 UTC, Sosssen commented on main.cpp
> +    std::cerr << "Provide only 2 indexes or none" << std::endl;
DON

2023-11-20 20:56 UTC, Sosssen commented on main.cpp
> +      for (int j = i; j < graphs.size(); j++) {
DON

2023-11-20 20:56 UTC, Sosssen commented on main.cpp
> +  return 0;
NO KURWA REACHABLE, ARGC == 3, BRAK JAKICHKOLWIEK ARGUMENTÓW (NEITHER INDEXES NOR -EEEEEEE)

2023-11-20 20:56 UTC, Sosssen commented on main.cpp
> +  return 0;
NO KURWA REACHABLE, ARGC == 3, BRAK JAKICHKOLWIEK ARGUMENTÓW (NEITHER INDEXES NOR -EEEEEEE)

2023-11-20 20:56 UTC, Sosssen commented on main.cpp
> +  }
DON

2023-11-20 20:56 UTC, Sosssen commented on main.cpp
>    }
tutaj nie wiem jak żeby logika została, chcesz to masz zielone na reformatting tego, zmieniłem w distance i mcs

2023-11-20 20:56 UTC, Sosssen commented on main.cpp
> +  if (argc == 4) {
MACIE kurwY POskie

2023-11-20 20:56 UTC, Sosssen commented on main.cpp
>    if (argc == 5) {
DON

2023-11-20 21:05 UTC, H3w9VH3F4L4Tq5MbsfRi commented on main.cpp
> +      for (int j = i; j < graphs.size(); j++) {
chyba jednak nie

2023-11-20 21:11 UTC, Sosssen approved these changes
łaaaaaa

2023-11-20 21:12 UTC, merged