File loading (as per Homenda's specs)
schizofrenicy/taio pull request #3
Opened 2023-11-07 10:25 UTC by H3w9VH3F4L4Tq5MbsfRi

2023-11-07 14:39 UTC, Sosssen requested changes
BIG REDDDDDD d-_-b

2023-11-07 14:39 UTC, Sosssen commented on graph.cpp
>  }
ustawienia vs Code -> Insert Final Newline i se to włącz, na końcu plików muszą być newliny

2023-11-07 14:39 UTC, Sosssen commented on main.cpp
> +void calculate_mcs() { std::cout << "calculating mcs" << std::endl; }
jak wyżej, newline

2023-11-07 14:39 UTC, Sosssen commented on main.cpp
> +int parse_arguments(int argc, char** argv, std::vector<Graph>& graphs);
tak jak ci mówiłem, czerwone
nie zmieniaj argumentów w `parse_arguments` - nie ma sensu parsować grafów, jak wgl wejście jest złe (wybrana zła opcja, niepodana ścieżka do pliku)

2023-11-07 14:39 UTC, Sosssen commented on main.cpp
> +    Graph::load_graphs_from_file(argv[1], graphs);
nie no kurwa, ale jak tu znowu wywołujesz `load_graphs_from_file` too już kompletnie nwm po chuj ten argument dodatkowy i wywołanie w mainie, usuń

2023-11-07 14:39 UTC, Sosssen commented on main.cpp
> +    Graph::load_graphs_from_file(argv[1], graphs);
dodatkowo zmień na argv[2] - w argv[1] będzie rodzaj funkcji, którą chcemy wywołać (size, distance, clique, mcs)

2023-11-07 14:39 UTC, Sosssen commented on graph.cpp
> +    std::cout << this->additional_data[i] << std::endl;
źle
https://stackoverflow.com/questions/15027282/c-for-each-pulling-from-vector-elements
odpowiedź Mariusa, masz 3 sposoby na zrobienie loopa po vectorze, wybierz sobie dowolny (trzeci najprostszy i najbliższy temu co teraz robisz)

2023-11-07 14:39 UTC, Sosssen commented on main.cpp
> +  for (int i = 0; i < (int)graphs.size(); i++) {
jak wyżej, zły for loop
ale to temp, więc do osrania może być

2023-11-07 14:39 UTC, Sosssen commented on graph.cpp
> +  if (!graph_file.is_open()) {
jakieś krótkie info czemu błąd

2023-11-07 14:39 UTC, Sosssen commented on graph.cpp
> +  if (graph_count <= 0) {
info o błędzie

2023-11-07 14:39 UTC, Sosssen commented on graph.cpp
> +      graph_file.close();
info o błędzie

2023-11-07 14:39 UTC, Sosssen commented on graph.cpp
> +      std::stringstream line_stream(current_line);
sam to rozwiązanie czytania linii wymyśliłeś, czy L?

2023-11-07 14:39 UTC, Sosssen commented on graph.cpp
> +          graph_file.close();
info o błędzie

2023-11-07 14:39 UTC, Sosssen commented on graph.cpp
> +          if (graphs[i].add_edge(j, k) == 1) {
info o błędzie

2023-11-07 14:39 UTC, Sosssen commented on graph.cpp
> +    while (!current_line.empty()) {
PO PIERWSZE: wczytasz tylko jeden graf (i tak się dzieje w przykładzie który mi podesłałeś, drugi graf idzie jako "additional info" do pierwszego grafu

PO DRUGIE: przy `eof()` też powinieneś dodać te linijkę do obsłużenia, bo aktualnie jak linijka posiada EOF (ale posiada dane) to ją osrywasz

2023-11-07 14:39 UTC, Sosssen commented on graph.cpp
> +  graph_file.close();
info o błędzie

2023-11-07 16:58 UTC, H3w9VH3F4L4Tq5MbsfRi commented on .vscode/settings.json
Samo się dodało
wyjebane, dodana reguła do .gitignore

2023-11-07 17:00 UTC, H3w9VH3F4L4Tq5MbsfRi commented on graph.cpp
>  }
done

2023-11-07 17:00 UTC, H3w9VH3F4L4Tq5MbsfRi commented on main.cpp
> +void calculate_mcs() { std::cout << "calculating mcs" << std::endl; }
done

2023-11-07 17:08 UTC, H3w9VH3F4L4Tq5MbsfRi commented on main.cpp
> +int parse_arguments(int argc, char** argv, std::vector<Graph>& graphs);
reverted

2023-11-07 17:09 UTC, H3w9VH3F4L4Tq5MbsfRi commented on main.cpp
> +    Graph::load_graphs_from_file(argv[1], graphs);
reverted

2023-11-07 17:10 UTC, H3w9VH3F4L4Tq5MbsfRi commented on main.cpp
> +    Graph::load_graphs_from_file(argv[1], graphs);
wywołanie usunięte wgl z parse_arguments

2023-11-07 17:27 UTC, H3w9VH3F4L4Tq5MbsfRi commented on graph.cpp
> +    std::cout << this->additional_data[i] << std::endl;
done

2023-11-07 17:27 UTC, H3w9VH3F4L4Tq5MbsfRi commented on main.cpp
> +  for (int i = 0; i < (int)graphs.size(); i++) {
spk

2023-11-07 17:38 UTC, H3w9VH3F4L4Tq5MbsfRi commented on graph.cpp
> +  if (!graph_file.is_open()) {
done

2023-11-07 17:39 UTC, H3w9VH3F4L4Tq5MbsfRi commented on graph.cpp
> +  if (graph_count <= 0) {
done

2023-11-07 17:40 UTC, H3w9VH3F4L4Tq5MbsfRi commented on graph.cpp
> +      graph_file.close();
done

2023-11-07 17:41 UTC, H3w9VH3F4L4Tq5MbsfRi commented on graph.cpp
> +      std::stringstream line_stream(current_line);
zarówno czytanie, jak i dzielenie linii znalezione w necie na przykładach

2023-11-07 17:44 UTC, H3w9VH3F4L4Tq5MbsfRi commented on graph.cpp
> +          graph_file.close();
done

2023-11-07 17:45 UTC, H3w9VH3F4L4Tq5MbsfRi commented on graph.cpp
> +          if (graphs[i].add_edge(j, k) == 1) {
done

2023-11-07 17:51 UTC, H3w9VH3F4L4Tq5MbsfRi commented on graph.cpp
> +  graph_file.close();
done

2023-11-07 18:02 UTC, H3w9VH3F4L4Tq5MbsfRi commented on graph.cpp
> +    while (!current_line.empty()) {
done

2023-11-07 21:44 UTC, Sosssen requested changes
KURWA

2023-11-07 21:44 UTC, Sosssen commented on .gitignore
> +.# Prerequisites
CO TO JEST, KURWA, CAŁY FOLDER OBECNY DODAJESZ DO GITIGNORE?????

2023-11-07 21:44 UTC, Sosssen commented on .gitignore
> +./vscode/
brak newline heheh

2023-11-07 21:44 UTC, Sosssen commented on graph.cpp
> +  for (auto s = this->additional_data.begin(); s != this->additional_data.end();
jak ty wpadłeś na skrót `s`? tylko pytanie

2023-11-07 21:44 UTC, Sosssen commented on main.cpp
> +    if (argc < 4) {
wróć do `!= 3`, nwm czemu to cofasz

2023-11-07 21:44 UTC, Sosssen commented on main.cpp
> -    Graph::load_graphs_from_file(argv[1], graphs);
AAAAA no w tym miejscu było dobrze przecież, gdzieś musisz te grafy wczytać, tera nigdzie nie wczytujesz

tylko żeby nie przekazywać parametru do `parse_arguments`, tutaj stworzyć se te tablicę grafów (albo wgl w `load_graphs_from_file` i zwrócić jako `out` parameter + sprawdzanie czy `load_graphs_from_file` się powiodło

2023-11-07 21:44 UTC, Sosssen commented on graph.cpp
> +      getline(graph_file, current_line);
KURWA. NIE DZIAŁA.

2023-11-08 00:00 UTC, Sosssen commented on graph.cpp
> +      getline(graph_file, current_line);
działa, to ja debil, a dokładniej WINDOWS

2023-11-08 00:04 UTC, Sosssen commented
pozwolę sobie skomentować co nie działało:
system dla psuw - w plikach które dostarczyłeś .txt koniec linii to dwa bajty (0D, 0A) <- najpierw `\r`, potem `\n` <- najpierw carriage return, potem newline

jest tak dlatego, że windows to system DLA PSUW i potrzebuje dwóch znaków żeby się kurwa dowiedzieć, że jest nowa linia

mój MACBOOK AIR M2 16GB RAM TEGO NIE OGARNĄŁ i przez to cały czas getline świrował
jak zmieniłem na plik po ludzku (zawierający '\n'), to działa idealnie (no prawie, patrz jeszcze jeden kom)
POzdrawiam

2023-11-08 00:15 UTC, Sosssen requested changes
już prawie, już prawie

2023-11-08 00:15 UTC, Sosssen commented on graph.cpp
> +        return 0;
może to znowu WINa systemu dla psuw, ale nie działa mi to -> gdy jest pusta linia, to automatycznie wyjdzie z while, czyli nie dojdzie do sprawdzenia eof, czyli nie zakończy poprawnie działania funkcji i przy poprawnym inputcie (nawet bez tych \r zajebanych)
jak ci to działa to weeiiirddd, bo oznacza to, że flaga eof jest ustawiana zanim tak naprawdę skończy się plik lol (no jak może się ustawić zanim linia jest pusta)

NIEMNIEJ -> mi działa dopiero, jak zaznaczony fragment wyniesie się POD while, POzdrawiam

2023-11-08 00:15 UTC, Sosssen commented on graph.cpp
> +        temp_int = stoi(temp_string);
opierdol wszystkie `stoi` w trycatche, bo ta funkcja nie ma obsługi errorów, po prostu zwraca int,
ale rzuca błąd `invalid_argument` jak nie może sparsować - stosowny komunikat, return 1 i jesteśmy w domu

2023-11-08 06:45 UTC, H3w9VH3F4L4Tq5MbsfRi commented on .gitignore
> +.# Prerequisites
pierdolnełem sie, fixed

2023-11-08 06:45 UTC, H3w9VH3F4L4Tq5MbsfRi commented on .gitignore
> +./vscode/
done

2023-11-08 06:46 UTC, H3w9VH3F4L4Tq5MbsfRi commented on graph.cpp
> +  for (auto s = this->additional_data.begin(); s != this->additional_data.end();
S jak string, mimo tego że jest to std::vector<std::string>::iterator
ale za to jak dam *s, to już dostanę stringa

2023-11-08 06:49 UTC, H3w9VH3F4L4Tq5MbsfRi commented on main.cpp
> +    if (argc < 4) {
BO TAK NA MAINIE JEST HEHEHEHEHEHE
DONE

2023-11-08 06:50 UTC, H3w9VH3F4L4Tq5MbsfRi commented on graph.cpp
> +      getline(graph_file, current_line);
RESOLVED

2023-11-08 06:53 UTC, H3w9VH3F4L4Tq5MbsfRi commented on main.cpp
> -    Graph::load_graphs_from_file(argv[1], graphs);
chyba done?
na najnowszym branchu
(ale pewnie się okaże że jednak wciąż jest chujowo)

2023-11-08 07:02 UTC, H3w9VH3F4L4Tq5MbsfRi commented on graph.cpp
> +        return 0;
nie wiem czy chodziło ci o POD WHILE w znaczeniu poza całego while
czy POD WHILE w znaczeniu pod linijkę z while (main.cpp 134)
dlatego sprawdziłem obie konfiguracje:

1. program wpada z nieskończoną pętle
2. program nie zapisuje jako atrybut ostatniej linijki


@
[plik_testowy.txt](https://github.com/schizofrenicy/taio/files/13293311/plik_testowy.txt)

2023-11-08 07:41 UTC, H3w9VH3F4L4Tq5MbsfRi commented on graph.cpp
> +        temp_int = stoi(temp_string);
Done

2023-11-08 13:12 UTC, Sosssen commented on main.cpp
> -    Graph::load_graphs_from_file(argv[1], graphs);
WCIĄŻ CHUJOWO

2023-11-08 14:41 UTC, Sosssen reviewed
do kodu już tyle uwag, jak śmignie na macos i win to jazda

2023-11-08 14:41 UTC, Sosssen commented on graph.cpp
> +  int graph_count = -1;
XD

2023-11-08 14:41 UTC, Sosssen commented on graph.cpp
> +  int graph_count = -1;
zadeklaruj bez inicjalizowania, kurwa, wypierdol to xD

2023-11-08 15:15 UTC, H3w9VH3F4L4Tq5MbsfRi commented on graph.cpp
> +        return 0;
RESOLVED

2023-11-08 15:19 UTC, H3w9VH3F4L4Tq5MbsfRi commented on main.cpp
> -    Graph::load_graphs_from_file(argv[1], graphs);
DONE, APPROVED

2023-11-08 15:29 UTC, Sosssen approved these changes
:)

2023-11-08 15:31 UTC, merged